### ISSUE TITLE
Notice: Undefined index: uploads_dir

### ISSUE THREAD

**Issue by facine** [siwapp/siwapp-sf3#1]
Hi, first all, thanks for this great work...

I'm testing this version and I get this error when try to edit the global settings here: http://my_siwapp/configuration/global_settings
Notice: Undefined index: uploads_dir in [MY_PATH]/src/Siwapp/ConfigBundle/Form/GlobalSettingsType.php on line 96

I haven't any experience with symphony and I can't fix it. Sorry

**Comment by ParisLiakos** [comment]
Thanks a lot for reporting it!
As far as i can see its something simple: `$data['uploads_dir']` needs an isset check there before accessing it.

**Comment by facine** [comment]
aham, but I can't find any "uploads_dir" or defaults in settings files, must we add some default value if it is not set?

**Comment by ParisLiakos** [comment]
aaaah, i am sorry...this is an unused variable..we can safely get rid of `$uploadsDir` completely

**Comment by facine** [comment]
But this variable is used for show the current logo:

```
        $data = $builder->getData();
        $uploadsDir = $data['uploads_dir'];
        $builder->get('company_logo')
            ->addModelTransformer(new CallbackTransformer(
                function ($filename) use (**$uploadsDir**) {
                    return $filename ? new File($filename, false) : null;
                },
                function ($file) {
                    return $file;
                }
            ))
        ;
```

**Comment by facine** [comment]
Oh! Thanks!!
