### ISSUE TITLE
[i18n] Localize "Are you sure?" confirmation alert

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#101]
The "Are you sure?" message in the javascript confirmation alert is currently not localized.

**Comment by ParisLiakos** [comment]
Thanks for opening the issue. New strings added, need translating :)
Also now the message is much more user friendly and not as general

**Comment by ParisLiakos** [comment]
I will probably release v1.0.3 with today's fixes after those translations here are ready
