### ISSUE TITLE
[Bug] Discounted amount on negative price items

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#105]
When an line item has a negative amount as unitary cost and a discount % is applied, the discounted amount is shown as positive when printed.

![captura](https://cloud.githubusercontent.com/assets/802183/22657819/26a0a3e6-ec98-11e6-8eb8-f7f6132af6da.PNG)

I think it is supposed to be negative (- amount), but not sure if it's the intended behavior.

**Comment by ParisLiakos** [comment]
I think it makes sense that way and its proper linguistics. Imagine saying that "the Discount is minus 10 euro" in real life. The discount verb already indicates that it is an amount to be subtracted from the total value.

**Comment by JMCA2** [comment]
You are right, giving it some thought I agree its more correct.

I was comparing it to the other siwapp version who used to show the minus sign I think
