### ISSUE TITLE
[Improvement] Force HTTPS connection

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#108]
While this can be manually achieved configuring a .htaccess file, I think it would be more user friendly if there was a checkbox on the setting allowing to force redirection to https:// for better security for those with SSL certificates.

**Comment by ParisLiakos** [comment]
This is out of scope of siwapp. This is better achieved by configuring the virtualhost or the htaccess like you mentioned, or the control panel each user uses.
It is not something that should be in the application logic, the application should be protocol and enviroment agnostic.
Not to mention the support overhead this would create..Imagine someone enabling the checkbox without configuring SSL on the server first..Siwapp would no longer be accessible
