### ISSUE TITLE
Make it clearer that the upgrade is actually a data import

### ISSUE THREAD

**Issue by herbdool** [siwapp/siwapp-sf3#115]
I spun my wheels on this for awhile until I thought I should at least try to run the upgrade script against the old database. Turns out that was the trick. But it's not clear from https://github.com/siwapp/siwapp-sf3/wiki/Upgrading that someone needs to create a new database, run the install commands, and then run the import.

**Comment by ParisLiakos** [comment]
Hi, thanks for the feedback. Good point, i updated the text there a bit. If you have some more suggestions, let me know.
