### ISSUE TITLE
virtual hosting ?

### ISSUE THREAD

**Issue by jseutens** [siwapp/siwapp-sf3#116]
I have a few small business owners who are currently using excell to write invoices. I do liked the old siwapp but want to migrate to the new one if i can use it with my hosting (root access is available)
Is there a way to give each client their own siwapp ?

thx

**Comment by ParisLiakos** [comment]
Sure, you can run multiple installations of siwapp in the same server. Just use different virtual hosts that each points to another siwapp installation, with different database.
