### ISSUE TITLE
Path to logo incorrect when printing or downloading pdf

### ISSUE THREAD

**Issue by herbdool** [siwapp/siwapp-sf3#118]
As far as I can tell, the template is using a relative path to the logo image but when printing it' no longer at the webroot so it can no longer find the logo. I believe the same goes for the pdf.

**Comment by ParisLiakos** [comment]
`<img src="{{ absolute_url(asset(settings.company_logo)) }}" alt="{{ settings.company_name }}" />`
it is using the absolute url as far as i can see. I also tried it on siwapp-sf3.rootatwc.com and it works correctly

**Comment by herbdool** [comment]
Ok I'll take another look and see why it wasn't working for me.

**Comment by josemi-ca** [comment]
@herbdool Maybe your template got imported from a legacy v0.4.x installation? That might be the issue

**Comment by herbdool** [comment]
@JMCA2 that sounds possible. Where are the templates stored?

**Comment by josemi-ca** [comment]
@herbdool The imported invoices template should be located at `/app/Resources/SiwappInvoiceBundle/views/Invoice/print.html.twig`

The template for estimates would be at `/app/Resources/SiwappEstimateBundle/views/Estimate/print.html.twig`

**Comment by herbdool** [comment]
@JMCA2 Thank you! I didn't need to keep the old templates so I've just emptied out app/Resources and cleared the cache. That fixes my issue.
