### ISSUE TITLE
PHP 7.2 Support

### ISSUE THREAD

**Issue by josemi-ca** [siwapp/siwapp-sf3#120]
PHP 7.2 has already reached Release Candidate phase and is expected to launch in 2 months.

7.2 could be added to travis-ci testing tu ensure compatibility.

http://php.net/archive/2017.php#id2017-08-31-1

**Comment by ParisLiakos** [comment]
I had to switch to phpunit6 for php7.2 compatibility. Done & added to travis for branch 1.1
