### ISSUE TITLE
Integrity constraint violations when upgrading from v0.41

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#14]
When using the upgrade path from a legacy v0.41 installation it causes an error and the import fails (also accessing siwapp causes 500 Internal Server Error).

`# php bin/console siwapp:upgrade-db:0.4-1.0 mysql DB_USER DB_NAME DB_PASS
Imported 15 Properties
Imported 7 Series
Imported 68 Taxes
Imported [REDACTED] Customers
Imported 0 Products
Imported 0 Estimates
Imported 0 RecurringInvoices
Imported [REDACTED] Invoices
Imported 1 Templates
You may have to perform additional actions in order to correctly port your templ                                                                                        ates.
You must copy your logo from the previous Siwapp instalation to "web/uploads".

  [Doctrine\DBAL\Exception\NotNullConstraintViolationException]
  An exception occurred while executing 'INSERT INTO customer (name, identifi
  cation, email, contact_person, invoicing_address, shipping_address) VALUES
  (?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, null]:
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot
  be null

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot
  be null

  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot
  be null

`

**Comment by JMCA2** [comment]
This was caused because a null entry on the "customer" table of the old database. Manually deleting the null entry from the old database fixes this error, but the upgrade path shouldn't require that.

**Comment by JMCA2** [comment]
@ParisLiakos 
The following error happens preventing the upgrade from completing. I think it's the only thing stopping from upgrade. Help would be really appreciated. Thanks

# php bin/console siwapp:upgrade-db:0.4-1.0 mysql DB_USER DB_NAME DB_PASS
Imported 15 Properties
Imported 7 Series
Imported 68 Taxes
Imported [REDACTED] Customers
Imported 0 Products
Imported 0 Estimates
Imported 0 RecurringInvoices
Imported [REDACTED] Invoices
Imported 1 Templates
You may have to perform additional actions in order to correctly port your templates.
You must copy your logo from the previous Siwapp instalation to "web/uploads".


  [Doctrine\DBAL\Exception\UniqueConstraintViolationException]
  An exception occurred while executing 'INSERT INTO customer (name, identifi
  cation, email, contact_person, invoicing_address, shipping_address) VALUES
  (?, ?, ?, ?, ?, ?)' with params ["CUSTOMER NAME", "CUSTOMER ID", "CUSTOMER EMAIL", "CONTACT PERSON", "INVOICING ADDRESS", "SHIPPING ADDRESS"]:
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'CUSTOMER NAME' for key 'cstm_idx'



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'CUSTOMER NAME' for key 'cstm_idx'



  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'CUSTOMER NAME' for key 'cstm_idx`

**Comment by ParisLiakos** [comment]
I just committed something for the first issue. Not sure about the second one.
Reading the error it seems like there is a unique index on the customer name database field, but we dont have one.
Can you tell me what is the output of
`php bin/console doctrine:schema:update`

**Comment by JMCA2** [comment]
`php bin/console doctrine:schema:update`
Before or after running the migration script?

Thanks

**Comment by JMCA2** [comment]
@ParisLiakos 
`php bin/console doctrine:schema:update`
Before or after running the migration script?

Thanks

**Comment by ParisLiakos** [comment]
Before. If it says that your database is already in sync and then the error happens, then we would have to find out where this unique index came from.

**Comment by JMCA2** [comment]
`# php bin/co                                                                                        nsole doctrine:schema:update
ATTENTION: This operation should not be executed in a production environment.
           Use the incremental update to detect changes during development and u                                                                                        se
           the SQL DDL provided to manually update your database in production.

The Schema-Tool would execute "47" queries to update the database.
Please run the operation by passing one - or both - of the following options:
    doctrine:schema:update --force to execute the command
    doctrine:schema:update --dump-sql to dump the SQL statements to the screen
`

**Comment by ParisLiakos** [comment]
ah :) Yes, that DB is definitely outdated. Are you using the same database with the old installation?
If so, then please use a different one.

**Comment by JMCA2** [comment]
Now I have siwapp-sf3 on a different database, and when running doctrine:schema:update on it it says: "Nothing to update - your database is already in sync with the current entity metadata."

But the upgrade path still fails with the UniqueConstraintViolationException above when executing:
`php bin/console siwapp:upgrade-db:0.4-1.0 DB_DRIVER DB_USER DB_PASSWORD DB_NAME`
 (with the details of the siwapp-sf1 database)

**Comment by ParisLiakos** [comment]
very weird. Please open
src/Siwapp/CustomerBundle/Entity/Customer.php
and find
private $name;
it should have an @ORM line above it..Can you paste it to me?

I dont understand why you have a unique index

**Comment by JMCA2** [comment]
Here is the line: ` * @ORM\Column(name="name", type="string", length=255)`
But, I understand this line is regarding the new database.

The error is when executing php bin/console siwapp:upgrade-db:0.4-1.0 with the details of the old siwapp-sf1 database for upgrade to siwapp-f3.

**Comment by ParisLiakos** [comment]
Yes. The script is supposed to copy the records from old DB to the new DB.
Is the unique index error complaining for the insert to the old DB?
If so, it means that siwapp-sf3 is also looking the old DB and not the new one. (app/config/parameters.yml should point to the new database)

**Comment by JMCA2** [comment]
Running siwapp:upgrade-db:0.4-1.0 makes changes to the original database, is it supposed to do that? or just import the changes to the new database (set in parameters.yml)?

**Comment by ParisLiakos** [comment]
It should not make changes to the old/original db. It should just import things in the new database, set in parameters.yml, yes

**Comment by JMCA2** [comment]
Regarding the first issue, supposed to be solved by commit 411794d I added the new code, and just tested the upgrade path without manually removing the null entry on the "customer" table of the old database. 

It still throws the same error on my first message (Integrity constraint violation: 1048 Column 'name' cannot
be null), I believe the commit has not fixed the issue.

**Comment by ParisLiakos** [comment]
Tried something else, should work now

**Comment by JMCA2** [comment]
Just tried the migration with the updated code. It works! :) I was able to complete the migration.
Thank you very much.

I believe this issue is fixed now. But the migration has caused another error #16
