### ISSUE TITLE
Implement select2 for tax selection

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#18]
On the invoice creation page, the old siwapp had a dropdown for selecting taxes, while in the new version the taxes are shown in a list with checkboxes.
This is a problem for setups with many kinds of taxes (>10) as it requires a lot of scrolling to add items to the invoice.
Example: [https://i.imgur.com/W7W7vje.png](https://i.imgur.com/W7W7vje.png)

**Comment by JMCA2** [comment]
Siwapp sf1 approach: [https://i.imgur.com/Jgz812k.png](https://i.imgur.com/Jgz812k.png)

**Comment by ParisLiakos** [comment]
Good point.

**Comment by ParisLiakos** [comment]
https://select2.github.io/ would solve this problem and with https://fk.github.io/select2-bootstrap-css/ it would look great too

**Comment by JMCA2** [comment]
It really does look really good! 👍

**Comment by ParisLiakos** [comment]
No need for extra stylesheets, the defaults look fine :) enjoy!

**Comment by JMCA2** [comment]
@ParisLiakos Thank you so much! siwapp-sf3 is looking good :D
