### ISSUE TITLE
Spanish language not working

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#19]
I understand from commit 3bf59774af3a653cf1ee3220fc0ee22b9b8a6160 that Spanish language is available.

However, I've changed the locale to _es_ on /app/config.yml, and the user language from "My Settings", but the interface still shows in English, even after clearing the prod cache.

**Comment by JMCA2** [comment]
Solved: intl PHP extension wasn't enabled. I think this should be documented.

**Comment by ParisLiakos** [comment]
Thanks, thats a good point. Btw no need to edit app/config.yml
