### ISSUE TITLE
Error 500 when searching customer

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#21]
Steps to reproduce:

When searching any term from the Customers section (/web/customer) search box, it causes an Internal Server Error instead of showing the results. The error doesn't happen when searching invoices, just when searching customers.

`[2016-11-14 19:10:43] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 395 near 'contact_person': Error: Class Siwapp\CustomerBundle\Entity\Customer has no field or association named contact_person" at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 395 near 'contact_person': Error: Class Siwapp\\CustomerBundle\\Entity\\Customer has no field or association named contact_person at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT c, SUM(CASE WHEN i.gross_amount IS NULL THEN 0 ELSE i.gross_amount END) AS gross_amount, SUM(CASE WHEN i.gross_amount IS NULL THEN 0 ELSE i.gross_amount END - CASE WHEN i.paid_amount IS NULL THEN 0 ELSE i.paid_amount END) AS due_amount FROM Siwapp\\CustomerBundle\\Entity\\Customer c LEFT JOIN c.invoices i WHERE c.name LIKE '%[SEARCH-TERM]%' OR c.identification LIKE '%[SEARCH-TERM]%' OR c.contact_person LIKE '%[SEARCH-TERM]%' GROUP BY c.id at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []`

The searched term is: [SEARCH-TERM]

**Comment by ParisLiakos** [comment]
Thanks for reporting this, i dont know how i missed it!
