### ISSUE TITLE
Repeated invoices numbers

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#22]
When creating new invoices, they are given repeated invoice numbers sometimes.

The series first number is correctly set in the Global Settings.

Screenshot showing the issue: https://i.imgur.com/hdmIQBx.png

**Comment by ParisLiakos** [comment]
Not sure about this one. It works ok for me. Can you identify a pattern maybe? Please also pull the latest code before further testing.
There is a query that runs to get the next number to use in AbstractInvoiceRepository class, which ends up looking like that:

`SELECT 
  MAX(i0_.number) AS sclr_0 
FROM 
  invoice i0_ 
WHERE 
  i0_.status <> 0
  AND i0_.series_id = 1`

if you change the series_id you can forsee what the next number of this series will be by adding one to the query result.

**Comment by JMCA2** [comment]
Ok. I'll do some testing and try to find a pattern. Will also try with the latest code.

I'll update with my findings later today

**Comment by JMCA2** [comment]
I've been able to reproduce the problem many times, but after applying commit 1199172d88ba47fee9dbcf47936b39fabaa758a7 it stopped happening. Reverted back and started happening again.

Not sure the reason this was happening, but it seems 1199172d88ba47fee9dbcf47936b39fabaa758a7 fixes it 👍

**Comment by ParisLiakos** [comment]
A lucky guess :P Thanks!
