### ISSUE TITLE
Missing jQuery UI image

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#24]
The CSS file includes:

`background:#dadada url("../bundles/siwappcore/vendor/jquery-ui/images/ui-bg_glass_75_dadada_1x400.png")`

The image bg_glass_75_dadada_1x400.png doesn't exist, generating an error on the logs:

`[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /bundles/siwappcore/vendor/jquery-ui/images/ui-bg_glass_75_dadada_1x400.png\" (from \"/web/css/b3ea8d8.css\") at /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/cache/prod/appProdUrlMatcher.php:445)"} []`

**Comment by ParisLiakos** [comment]
Nice, it was also in my logs, but i never noticed. Thanks!!
