### ISSUE TITLE
Bug: Mandatory tax selection

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#28]
Related issue: #18

Since the new select2 implementation, saving an invoice is not allowed unless all items have a tax selected. There's no option for not adding a tax.

**Comment by JMCA2** [comment]
86c152d makes tax not required when creating an invoice. But there's still no way to remove an active tax from an line item :P

**Comment by ParisLiakos** [comment]
Hmm, what do you mean, i click the small `x` left to the tax and the field empties. Then i click save invoice button, tax is no longer there

**Comment by JMCA2** [comment]
![captura](https://cloud.githubusercontent.com/assets/802183/20650902/00ac1c56-b4da-11e6-8d8e-dacb582ab176.PNG)

**Comment by JMCA2** [comment]
I don't see an `x` to remove the applied tax, or any way to un-select a tax

**Comment by ParisLiakos** [comment]
Ah :) You dont see the select2 widget, you probably need to rebuild your assets.
Thats what i see:

![image](https://cloud.githubusercontent.com/assets/656465/20650929/09fa5ec2-b4e3-11e6-972b-a84eaf03949c.png)

Run `php bin/console assetic:dump --env=prod`

But even with the standard html multiselect element you can unselect a tax, by Ctrl+clicking it.

**Comment by JMCA2** [comment]
Ohh yeah. My bad. Thank you :)
