### ISSUE TITLE
Auto-complete previously used product descriptions

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#29]
It would be very useful if on the new invoice page, previously used product descriptions were shown as auto-complete suggestions too, just like when typing on the Customer field.
It worked like that on the old siwapp.

**Comment by ParisLiakos** [comment]
This already happens for the product field, not the description one. It searches for the product reference code.
Not sure how performant would be to autocomplete descriptions on databases with a lot of products

**Comment by JMCA2** [comment]
In my experience with the old siwapp version, it worked well with a few hundred products.

**Comment by ParisLiakos** [comment]
Running `php bin/console assets:install` is needed after this change

**Comment by JMCA2** [comment]
This doesn't seem to be working for me, even after running `php bin/console assets:install` No suggestions for previously used descriptions, show up when typing on the item description field when creating an invoice

PS: Is running `php bin/console assets:install` required also for new installations? I did, just to make sure.

**Comment by ParisLiakos** [comment]
no, for new installations 
`php bin/console assetic:dump --env=prod` is enough

it is supposed to check descriptions from existing products. Weird, it works for me, do you maybe have any javascript error? Check your console

**Comment by JMCA2** [comment]
Okay, right. As I understand this only autocompletes existing created products,

My feature request (and old siwapp behaviour) was to auto-compete with descriptions previously used on other invoices (not only saved products).

**Comment by ParisLiakos** [comment]
Sorry, my bad. I fixed it to check exitsting items instead

**Comment by JMCA2** [comment]
Thank you so much! 😄

**Comment by JMCA2** [comment]
This doesn't seem to be currently working for me, suggestion don't appear and this error appears on the browser console:

> Uncaught ReferenceError: addInvoiceItemDescriptionAutocomplete is not defined
    at HTMLDocument.<anonymous> (new:242)
    at i (core.js:2)
    at Object.fireWith [as resolveWith] (core.js:2)
    at Function.ready (core.js:2)
    at HTMLDocument.J (core.js:2)

**Comment by ParisLiakos** [comment]
ah, you need to refresh your assets
`php bin/console assetic:dump --env=prod` if you use the production mode, 
`php bin/console assets:install` for dev mode

**Comment by JMCA2** [comment]
It's a new installation, following all install steps (including `php bin/console assetic:dump --env=prod`)

**Comment by ParisLiakos** [comment]
Which page then? new invoice? or edit invoice?

**Comment by JMCA2** [comment]
Both, edit and new invoice

**Comment by ParisLiakos** [comment]
For sure you have some caches. I just tried a fresh install and it works. Try the following:
php bin/console cache:clear --env=prod
php bin/console assets:install --env=prod
php bin/console assetic:dump --env=prod

**Comment by JMCA2** [comment]
I had previously cleared cache, but for some reason it seems it didn't really clear. Autocomplete is working indeed. Sorry, my bad.

**Comment by ParisLiakos** [comment]
Ah, great, no problem
