### ISSUE TITLE
Error upgrading from v0.4.x

### ISSUE THREAD

**Issue by facine** [siwapp/siwapp-sf3#3]
Hi, I get this error and data is not imported:

```
$ php bin/console siwapp:upgrade-db:0.4-1.0 mysql siwapp siwapp siwapp_old_data localhost
Imported 14 Properties
Imported 5 Series
Imported 4 Taxes
Imported 962 Customers
Imported 0 Products
Imported 326 Estimates
Imported 0 RecurringInvoices

                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index:                                   
                                                             

siwapp:upgrade-db:0.4-1.0 [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <driver> <username> <password> <db> [<host>] [<port>]
```

any idea?

**Comment by ParisLiakos** [comment]
Hm this message is not very helpful. If i am guessing correctly the error is on Invoice migration.
Can you run this with the `-vvv` flag? We would get a backtrace then (hopefully)

**Comment by facine** [comment]
`$ php bin/console siwapp:upgrade-db:0.4-1.0 mysql siwapp siwapp siwapp_old_data localhost -vvv > error.log
[2016-07-13 20:08:43] php.INFO: getEntityManager is deprecated since Symfony 2.1. Use getManager instead {"type":16384,"file":"/vendor/doctrine/doctrine-bundle/Registry.php","line":71,"level":32767,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"/vendor/doctrine/doctrine-bundle/Registry.php","line":71,"function":"trigger_error"},{"file":"/src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php","line":79,"function":"getEntityManager","class":"Doctrine\\Bundle\\DoctrineBundle\\Registry","type":"->"},{"file":"/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php","line":256,"function":"execute","class":"Siwapp\\CoreBundle\\Command\\UpgradeFrom04Command","type":"->"},{"file":"/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php","line":831,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php","line":186,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php","line":80,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php","line":117,"function":"doRun","class":"Symfony\\Bundle\\FrameworkBundle\\Console\\Application","type":"->"},{"file":/bin/console","line":29,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"}]} 

                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index:                                   
                                                             

Exception trace:
 () at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:320
 Symfony\Component\Debug\ErrorHandler->handleError() at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:320
 Siwapp\CoreBundle\Command\UpgradeFrom04Command->setCommonInvoiceProperties() at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:254
 Siwapp\CoreBundle\Command\UpgradeFrom04Command->importInvoices() at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:83
 Siwapp\CoreBundle\Command\UpgradeFrom04Command->execute() at /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:831
 Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /bin/console:29

siwapp:upgrade-db:0.4-1.0 [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <driver> <username> <password> <db> [<host>] [<port>]`

**Comment by ParisLiakos** [comment]
Ah, it seems that the invoice is referring to a Series that it does not exist..I should add a check for that.
Thanks for the verbose output

**Comment by ParisLiakos** [comment]
Can you check again? (clean your database first) 
I just committed a potential fix
https://github.com/siwapp/siwapp-sf3/commit/853801074b7994145bb9af9e78c31fbff4b3727e

**Comment by facine** [comment]
Now I get duplicate errors, any way before customer email was optional and now is required, can this be a problem?:
```
$ php bin/console siwapp:upgrade-db:0.4-1.0 mysql siwapp siwapp siwapp_old_data localhost -vvv
Imported 14 Properties
Imported 5 Series
Imported 4 Taxes
Imported 962 Customers
Imported 0 Products
Imported 326 Estimates
Imported 0 RecurringInvoices
Imported 2395 Invoices
Imported 2 Templates
You may have to perform additional actions in order to correctly port your templates.

                                                                                                                                                                                               
  [Doctrine\DBAL\Exception\UniqueConstraintViolationException]                                                                                                                                 
  An exception occurred while executing 'INSERT INTO customer (name, identification, email, contact_person, invoicing_address, shipping_address) VALUES (?, ?, ?, ?, ?, ?)' with params […..]:                                                    
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'UNIQ_81398E0949E7720D'                                                                                     
                                                                                                                                                                                               

Exception trace:
 () at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at /vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
 Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:175
 Doctrine\DBAL\Statement->execute() at /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:281
 Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() at /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1018
 Doctrine\ORM\UnitOfWork->executeInserts() at /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:378
 Doctrine\ORM\UnitOfWork->commit() at /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:356
 Doctrine\ORM\EntityManager->flush() at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:88
 Siwapp\CoreBundle\Command\UpgradeFrom04Command->execute() at /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:831
 Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /bin/console:29

                                                                                                            
  [Doctrine\DBAL\Driver\PDOException (23000)]                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'UNIQ_81398E0949E7720D'  
                                                                                                            

Exception trace:
 () at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
 Doctrine\DBAL\Driver\PDOStatement->execute() at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:165
 Doctrine\DBAL\Statement->execute() at /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:281
 Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() at /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1018
 Doctrine\ORM\UnitOfWork->executeInserts() at /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:378
 Doctrine\ORM\UnitOfWork->commit() at /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:356
 Doctrine\ORM\EntityManager->flush() at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:88
 Siwapp\CoreBundle\Command\UpgradeFrom04Command->execute() at /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:831
 Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /bin/console:29

                                                                                                            
  [PDOException (23000)]                                                                                    
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'UNIQ_81398E0949E7720D'  
                                                                                                            

Exception trace:
 () at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
 PDOStatement->execute() at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
 Doctrine\DBAL\Driver\PDOStatement->execute() at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:165
 Doctrine\DBAL\Statement->execute() at /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:281
 Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() at /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1018
 Doctrine\ORM\UnitOfWork->executeInserts() at /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:378
 Doctrine\ORM\UnitOfWork->commit() at /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:356
 Doctrine\ORM\EntityManager->flush() at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:88
 Siwapp\CoreBundle\Command\UpgradeFrom04Command->execute() at /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:831
 Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /bin/console:29

siwapp:upgrade-db:0.4-1.0 [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <driver> <username> <password> <db> [<host>] [<port>]

```

Thanks!

**Comment by facine** [comment]
I've forgotten say than when fails, no data are imported. The log says that are imported but not.

**Comment by ParisLiakos** [comment]
Good point for the email. But i think this error comes up because of the identification. Apparently in your customers its everywhere an empty string.
I pushed https://github.com/siwapp/siwapp-sf3/commit/c65741a61d60361a55c069a5126ac81a914827f7 it should help.

I guess the last step would be to make the email field nullable, but please try this

**Comment by facine** [comment]
Now I get:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'XXXXXXXX' for key 'UNIQ_81398E0949E7720D' 

I have different customers with the same legal ID, for example some spanish public organizations...

**Comment by ParisLiakos** [comment]
ah, i see...then this means that the unique index there needs to be removed if we have usecases like that!

**Comment by ParisLiakos** [comment]
ok, i removed the unique index, and made the email non-required.

you should run `php bin/console doctrine:schema:update --force` after pulling the change.,

let me know how it goes now. thanks a lot for your help!

**Comment by facine** [comment]
I can not see any change, have you pushed the commit?

Thanks!

**Comment by ParisLiakos** [comment]
Ugh, you are right, i forgot to push, Did that now

**Comment by facine** [comment]
Great! @ParisLiakos ++! No errors or warnings.

But there are some things:
- Should we import the logo of the company?
- This new customer system allow duplicate customers, the previous version had a slug name field to prevent it.

Thanks!

**Comment by ParisLiakos** [comment]
Not sure about the logo..Its not very straightforward where we can copy it from. Maybe people can do this manually.
I opened an issue for slugs. Now that we removed unique index from identification, its probably needed

**Comment by ParisLiakos** [comment]
I guess we can close this now. Thanks again for your help :)
