### ISSUE TITLE
Bug: Line amount and discount not working on template

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#31]
Both `{{item.discount_amount|localizedcurrency(settings.currency, app.request.locale)}}` and `{{item.gross_amount|localizedcurrency(settings.currency, app.request.locale)}}` show the line discount/gross amount as being 0.

This is the same as what happened with #25

**Comment by JMCA2** [comment]
Screenshot:

![captura](https://cloud.githubusercontent.com/assets/802183/20651091/8d32aaa6-b4de-11e6-8c69-0aa4ae588629.PNG)

**Comment by ParisLiakos** [comment]
Try with `discount` instead of `discount_amount` and `getGrossAmount()` instead of `gross_amount` (its computed/dynamic)

**Comment by ParisLiakos** [comment]
I guess i should do #17 sooner or later

**Comment by JMCA2** [comment]
It works with `discount` and `getGrossAmount()` indeed.

The variable names used on `/src/Siwapp/InvoiceBundle/Resources/views/Invoice/print.html.twig` are incorrect then

**Comment by ParisLiakos** [comment]
Ah, you are right...maybe i shoud make `discount_amount` working again :)

**Comment by JMCA2** [comment]
That would be nice :) It will also make existing conditionals such as `{% if invoice.discount_amount %}` work too

**Comment by ParisLiakos** [comment]
`discount_amount` and `gross_amount` work again now.. I will further try to make this consistent.

**Comment by JMCA2** [comment]
Awesome! Thank you!
