### ISSUE TITLE
Bug: -0,00€ discount on negative amount items

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#32]
Discovered a small bug: When an line item on an invoice has a negative amount and no discount is set, the line discount shows as -0,00€.
It should read 0,00€ instead (just as with positive amount items).

![captura](https://cloud.githubusercontent.com/assets/802183/20651350/de3ab056-b4e3-11e6-9ca8-5c7ea06febd4.PNG)

**Comment by ParisLiakos** [comment]
Thanks. We should not have minus discount amounts for items anymore.
