### ISSUE TITLE
i18n: Spanish translation fixes

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#33]
- [x] On the invoices page, the column title for the due amount currently reads "Vencido" in the Spanish translation. The correct term would be: "Debido".

- [x] In the Recurring invoices section, the frequency column is translated as "Frequencia". It should read "Frecuencia" instead.

- [x] In the user settings/profile (/web/profile/edit) locales is translated as "Regionalización". It should read "Configuración regional" instead.

- [x] The add payment button is currently translated as "Agregar pago", a better translation would be "Añadir pago".

- [x] The updated settings message translation has a typo. Currently "Ajustes actualziados". Should read "Ajustes actualizados" instead.

- [x] The "Invoice(s) deleted." text for the bulk deletion option is in English ". The translation would be "Factura(s) borrada(s).".

- [x] The "Approved" estimate status translation contains a typo. Currently "Aprovado". Should read "Aprobado".

- [x] The "Max occurrences" translation ("Número máximo de ocurrencias") it's too long and doesn't fit on the label space. It should be replaced with a shorter translation: "Máx. repeticiones".

- [x] In the individual invoice pages, the terms for status ("Opened", "Closed", "Overdue" and "Draft") are not translated. The translations would be "Abierta", "Cerrada", "Vencida" and "Borrador" (same terms used on the list of invoices). Maybe the status name on the individual invoice page is not localized?

- [x] On the global settings page, the terms: "Name", "Value", "Active", "Is default", "First Number" and  "Enabled" are not translated. The translations would be "Nombre", "Valor", "Activo", "Por defecto", "Primer número" and "Habilitado".

- [x] The "Invoice [NUMBER]" title on the edit invoice page is not localized. It should read "Factura".

**Comment by JMCA2** [comment]
I'll prepare updated locale files soon addressing all these

**Comment by JMCA2** [comment]
The pull request fixes most issues, but these are not localized on the software:

> - [ ] In the individual invoice pages, the terms for status ("Opened", "Closed", "Overdue" and "Draft") are not translated. The translations would be "Abierta", "Cerrada", "Vencida" and "Borrador" (same terms used on the list of invoices). Maybe the status name on the individual invoice page is not localized?
> - [ ] On the global settings page, the terms: "Name", "Value", "Active", "Is default", "First Number" and "Enabled" are not translated. The translations would be "Nombre", "Valor", "Activo", "Por defecto", "Primer número" and "Habilitado".

**Comment by JMCA2** [comment]
@ParisLiakos Could you please take a look at the two non-localized texts mentioned above? Thanks

**Comment by ParisLiakos** [comment]
Settings labels for taxes and series should be taken care of now. Need to think a bit more for invoice statuses

**Comment by ParisLiakos** [comment]
Status should also be fixed now, no need for new translations.
Please check and close this issue, thanks!

**Comment by JMCA2** [comment]
It works. Confirmed. Closing.
