### ISSUE TITLE
Usability issue: Invoice should be automatically saved before sending email

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#34]
I think the "send invoice by email button" should both save the invoice + send it by email, instead of just email it.

The user might edit an invoice and then click the email button, and believe the updated version was sent, but the old version was sent instead.

That's how it worked on the old siwapp, the button reads "Save and send by email".

This simple change could prevent many mistakes.

**Comment by ParisLiakos** [comment]
hmm, you are right..in the edit form those links/actions on top should go to bottom and become "Save and XX"

**Comment by JMCA2** [comment]
Yeah, I think that would be a good approach.
And maybe a button for #46 could be placed at the top where the current buttons are.

**Comment by JMCA2** [comment]
I see this is under the v1 milestone, while the other issues are under 1.1 or 2.0.
Does it means an official stable 1.0 release is coming and this is the only thing left to fix? :)

**Comment by ParisLiakos** [comment]
Exactly. I want v1.0 to be a direct port of v0.4.1 (well as much as possible). 
Now with your help i think we quite achieved it. There are of course some differences, eg like no tags or that templates are not editable in WYSIWYG anymore, but those are informed decisions that i made :)

I guess polishing the wiki a bit and adding a `Help` link in siwapp to it should also be done.. But this is minor i think.

**Comment by JMCA2** [comment]
I've been doing pretty intense testing of the current app in many scenarios with a QA-ish approach. I've been siwapp v0.4.1 on a daily basis for a really long time, so I wanted to make sure it being rock solid before migrating my current years worth of invoices database and fully switching to the new app.

The only current flaw I see is this usability issue. I've found myself emailing an incorrect invoice to an angry client, just to later realize changes have not been saved :P This is important since it's easy for that to happen, specially for users accustomed to the old app workflow.

In my opinion, with that fixed, it would be production-ready. Regarding the wiki, for the release, I would suggest adding a page there with the template variables (copy-paste from c84ee48ed2726f707d031d7ef1416da28706b9df).

**Comment by ParisLiakos** [comment]
Please, accept my apologies. I thought that the pattern "upper buttons are links lower buttons are actions" was clear, but apparently styling the upper links as buttons and not links did not help.

**Comment by ParisLiakos** [comment]
maybe we could fix this just by changing the styling to show them as links instead?

**Comment by ParisLiakos** [comment]
Or this 
![image](https://cloud.githubusercontent.com/assets/656465/21294177/aa552bc4-c53f-11e6-993f-ecf87e7fa4d4.png)

**Comment by JMCA2** [comment]
I think the second option (save+email) makes more sense, because if you edit an invoice before emailing it, it's obvious you'd want to send the updated version. And if no changes have been made, it won't be modified anyway.

The second approach would work either with the current buttons location (which look nicer, I think) or at the bottom (as in the screenshot).

**Comment by ParisLiakos** [comment]
This needs some extensive testing, but it works fine locally

**Comment by JMCA2** [comment]
I've been doing some extensive testing. I'll report the found issues.

**Comment by ParisLiakos** [comment]
Thank you very, very much for your testing. Siwapp v1 will really owe you very much for its existence :)

**Comment by JMCA2** [comment]
Glad I'm able to help :) And thank you so much for creating this awesome port.
