### ISSUE TITLE
Usability improvement: Email subject

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#35]
Currently, the email subject for invoices sent through the app is just "INVOICE-NUMBER".

I think it would be better if it was something like "[[Invoice: INVOICE-NUMBER]]" instead. 

Customers might not notice the email unless opening the received email, since there's no indication of the email being an invoice on its subject.

This small change would make it more user-friendly and less confusing.

**Comment by ParisLiakos** [comment]
You mean including square brackets? I agree that prefixing subject with `Invoice-` would make it better

**Comment by JMCA2** [comment]
I think the square brackets would be a nice addition, but the point is to include the Invoice word on the subject (such as Invoice: _NUMBER_) so that it is recognized by clients as that.

The "Invoice" word is already translated as `invoice.invoice` (included in my PR #39).
