### ISSUE TITLE
Bug: Migrated invoices not marked as overdue

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#36]
When upgrading from v0.4.x, the invoices marked as "overdue" (past their due dates) on the old installation, are set as "opened" on the new installation.

Manually editing the invoices automatically sets them as "overdue".

**Comment by JMCA2** [comment]
This seems to be solved somehow. I've re-tested doing a new migration now with the same database and the latest code, and it worked well, with overdue invoices being ported as "overdue" and not "opened" as before.
I'll close this for now then :)

**Comment by ParisLiakos** [comment]
Ah, good to hear, thanks for checking again!
