### ISSUE TITLE
Bug: Recurring invoices saved as draft

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#38]
I've noticed than when creating pending recurring invoices, they are created as drafts.

I guess they're supposed to be saved as opened non-draft invoices, and maybe also automatically sent by email (?). But they are just saved as drafts and also not sent by email.

There's no error on the logs regarding this, and I was able to reproduce it both from the "Create pending invoices" button on the UI and the `php bin/console siwapp:recurring:generate-pending` cron command.

**Comment by ParisLiakos** [comment]
Not sure about that, i will think...Looking the old siwapp it was creating open invoices, i dont see any sending email action. I thought creating drafts is more conservative and ok...but well open is ok too i think

**Comment by JMCA2** [comment]
I thinkopening invoices (instead of draft) but not sending them would be something balanced. It makes the process quicker, but also allows the user to review them before sending,

**Comment by ParisLiakos** [comment]
Ok, i agree. I did that, we can revisit if needed.
