### ISSUE TITLE
Only support PHP 7

### ISSUE THREAD

**Issue by ParisLiakos** [siwapp/siwapp-sf3#41]
Now that PHP 7.1 is out, i consider dropping PHP 5.6 support.
This will allow us to take advantage of 7.x features like typehinting etc.

Also PHP 5.6 becomes end of life end of the year.

**Comment by JMCA2** [comment]
I think it's a good idea. There are now two 7.x releases, and 7.0 has been out for over a year.  The performance improvements are also very significant.
