### ISSUE TITLE
Update to Symfony v3.2

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#42]
Symfony v3.2 has been released already (http://symfony.com/blog/symfony-3-2-0-released) and contains many improvements.

Also, I believe this is the first Symfony version to officially support PHP 7.1 (they were released at the same time, actually).

**Comment by ParisLiakos** [comment]
Thanks for opening the issue. I just updated to Symfony 3.2 and took care of deprecations. Had to also do some fixes for travis
