### ISSUE TITLE
Assetic Error

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#44]
I've noticed many instances of this error on the prod.log file. I believe this wasn't happening before, so it might have been introduced with one of the latest changes.

`assetic.ERROR: The template "SecurityBundle:Collector:security.html.twig" contains an error: Unknown "profiler_dump" function in "SecurityBundle:Collector:security.html.twig" at line 180. [] []`

**Comment by ParisLiakos** [comment]
It should not appear again
