### ISSUE TITLE
Manually set as sent by email

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#46]
One missing small feature compared to the old app, is the ability to manually set an invoices as sent by email (for example, by having a checkbox on the edit page).
It would be useful to log an invoice as already sent to a customer by other means.

**Comment by ParisLiakos** [comment]
I made both this and forcefully closed editable in the same way as old app :)

**Comment by ParisLiakos** [comment]
Ah, the new strings probably need translation now

**Comment by JMCA2** [comment]
This issue can be closed after #52 merge
