### ISSUE TITLE
Show real-time totals when editing

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#47]
It would be very useful if the totals were updated in real-time when editing an invoice (just like on the old app), instead of having to save the invoice to see the amount.

**Comment by ParisLiakos** [comment]
Dump your assets again..and this should work. Looks like it works correctly but didnt test it extensively. If you see everything works please close this issue. Thank you very much!

**Comment by JMCA2** [comment]
I've been testing this, it works well 👍 

Only one small issue to consider:
On a brand-new installation, this happens (notice the `false` amounts):
![captura](https://cloud.githubusercontent.com/assets/802183/21288361/61618f52-c481-11e6-80b3-556ebfd26064.PNG)

This issue only happens when no invoice series are created/enabled. No big deal, but maybe this should also work when no series are still created (or otherwise, create a default series when installing the application, to prevent this).

**Comment by ParisLiakos** [comment]
Thanks for checking. This bug should be fixed now
