### ISSUE TITLE
YUI Compressor replacement

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#48]
It would be better if YUI was replaced by some pure PHP alternative for better compatibility, so the app can be installed on shared hosting without the need to install java/nodejs/etc.

Also YUI has been deprecated and is no longer maintained by Yahoo, with Symfony strongly advising to stop its use.

**Comment by ParisLiakos** [comment]
I am not aware of any pure PHP solution that is widely supported and i really think that installing java is a lot easier than having to mess with nodejs and npm for uglify which is the current suggestion by symfony.

**Comment by ParisLiakos** [comment]
But i guess we can completely drop compressors..Its not like siwapp is a public facing app; we dont really have to care that much for bandwith and whether our assets are minimized.

**Comment by JMCA2** [comment]
+1


That would make things easier, it's not really needed for an internal app

**Comment by ParisLiakos** [comment]
Great! That should take care of it ^^

**Comment by JMCA2** [comment]
Thanks 😊
