### ISSUE TITLE
Include tax percentage next to tax name

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#49]
Right now item taxes are shown on invoices like this:
![captura](https://cloud.githubusercontent.com/assets/802183/21049654/6f39906e-be16-11e6-9015-e8349677b9c2.PNG)

It would be an improvement if the percentage was shown in brackets, like this:
![captura](https://cloud.githubusercontent.com/assets/802183/21049671/86972a14-be16-11e6-84ad-f1cafe9c351b.PNG)

**Comment by ParisLiakos** [comment]
we could easily add the value in the tax's label, another approach would also be the one in the demo data
![image](https://cloud.githubusercontent.com/assets/656465/21073695/ab6c3162-beee-11e6-9c3a-4084537dba6b.png)

But i guess your suggestion is better..No point duplicating info

**Comment by JMCA2** [comment]
Yeah, it would also be easier in case changing the percentage is necessary, using the demo data approach it would require replacing the percentages twice

**Comment by ParisLiakos** [comment]
You are absolutely right

**Comment by JMCA2** [comment]
@ParisLiakos I am not seeing this working with the updated code.
It seems to be working just as before, without the % being printed:

![captura](https://cloud.githubusercontent.com/assets/802183/21288401/784e9f7e-c482-11e6-96f6-f67239da6630.PNG)

**Comment by ParisLiakos** [comment]
@JMCA2 where is that screenshot from?

**Comment by JMCA2** [comment]
Default invoice template. `/invoice/XXX/show/print`

Fresh install with latest code

**Comment by ParisLiakos** [comment]
Thanks. I always forget to check print templates
