### ISSUE TITLE
Instructions for Internationalization

### ISSUE THREAD

**Issue by facine** [siwapp/siwapp-sf3#5]
Hi, I'm trying to translate Siwapp to spanish...

Can anyone give me any instructions for extract the strings?

I'm here: http://symfony.com/doc/current/best_practices/i18n.html
and here: http://jmsyst.com/bundles/JMSTranslationBundle/master/usage

But I can see the strings, only the id.

Any idea?

**Comment by ParisLiakos** [comment]
You can find the english translations into:
src/Siwapp/*/Resources/translations/*.en.yml

You can copy each file to 
src/Siwapp/*/Resources/translations/*.es.yml
and work there

**Comment by facine** [comment]
Hi again, I've placed the spanish translation files and cleared the cache and don't work, any idea?

Thanks!

**Comment by ParisLiakos** [comment]
Hi! Could it be that you have selected a locale that is not "es" but es_STH? eg not "Spanish", but "Spanish (Spain)"?
Also note that when changing locale you have to logout and then log back in.

**Comment by facine** [comment]
Hi, I'm using "es" locale, this is my test commit: https://github.com/facine/siwapp-sf3/commit/7a6f70eeda378c142710e7f7176f712434c9ad7e and I'm doing re-login.

There is no error in var/log
Any idea?

**Comment by ParisLiakos** [comment]
It worked for me. Did you clear the "prod" logs or "dev"?
Maybe do `sudo rm -rf var/cache/prod`

Also, you can use the dev mode under /app_dev.php
There you also have the helpful bottom bar which gives some nice details for translations

**Comment by facine** [comment]
Thanks! now works.
