### ISSUE TITLE
Update spanish translation for bulk_pdf

### ISSUE THREAD

**Issue by ParisLiakos** [siwapp/siwapp-sf3#51]
Commit aeb79459d4858f596c0f363258c4ecfbfc8e4129

Google suggests "Descargar seleccionados como PDF" but i am not sure

**Comment by JMCA2** [comment]
"Descargar seleccionados como PDF" is correct for estimates, but it should be "seleccionadas" for invoices (feminine word).

I've committed the translations on PR #52 :)
