### ISSUE TITLE
Undefined variable error when migrating from old app

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#56]
When migrating a v0.4.1 database to the new version (using the latest code) using the command path, the process fails throwing this error:

# php bin/console siwapp:upgrade-db:0.4-1.0 [DB connection details]
Imported 15 Properties
Imported 7 Series
Imported 68 Taxes

[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined variable: name

**Comment by ParisLiakos** [comment]
Can you run the command again with `-v` parameter and paste the output here?

**Comment by ParisLiakos** [comment]
btw, also pull latest code and run 
`php bin/console doctrine:schema:update --force`

**Comment by JMCA2** [comment]
I've updated to the latest code, cleared cache and also run `php bin/console doctrine:schema:update --force`.
Executed the command again with the verbose parameter:

> # php bin/console siwapp:upgrade-db:0.4-1.0 [DB details] -v
Imported 15 Properties
Imported 7 Series
Imported 68 Taxes
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined variable: name

Exception trace:
 () at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:168
 Siwapp\CoreBundle\Command\UpgradeFrom04Command->importCustomers() at /src/Siwapp/CoreBundle/Command/UpgradeFrom04Command.php:83
 Siwapp\CoreBundle\Command\UpgradeFrom04Command->execute() at /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /bin/console:29

siwapp:upgrade-db:0.4-1.0 [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <driver> <username> <password> <db> [<host>] [<port>]

**Comment by ParisLiakos** [comment]
I made the email required for clients and your import has some customers without email.
The workaround i did for customers from old siwapp that are missing email is to append '@upgradefrom04.fixme' to the customer's name, so that the email is not empty

**Comment by JMCA2** [comment]
Ok cool. Thank you! Just tried again and it worked 👍
