### ISSUE TITLE
Implement slug for customer

### ISSUE THREAD

**Issue by ParisLiakos** [siwapp/siwapp-sf3#6]
See https://github.com/siwapp/siwapp-sf3/issues/3#issuecomment-232595982

**Comment by ParisLiakos** [comment]
Or maybe we make the email required and unique..Unless there is a usecase two customers share the same email?

**Comment by facine** [comment]
I think is better implement slug, now email is optional...

**Comment by ParisLiakos** [comment]
I made the email required and unique after all and made the upgrade script account for that.
I dont see any usecase of a customer without email, everyone has an email in our days and its actually needed for the email function.
I think its better solution than implementing slug, so i am closing this one. Feel free to reopen if you see a usecase where the email could be empty or duplicated?

Thanks!
