### ISSUE TITLE
Require email+name when creating an invoice

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#65]
According to https://github.com/siwapp/siwapp-sf3/issues/6#issuecomment-263124573 and https://github.com/siwapp/siwapp-sf3/issues/56#issuecomment-267842968 it seems having an email address for each invoice it's required by the app, but currently it is possible to create a new invoice without an email.

The email field should be required.

**Comment by ParisLiakos** [comment]
Good point

**Comment by ParisLiakos** [comment]
Email and name actually..I really cant think of a usecase of an invoice without client name & email :)

**Comment by JMCA2** [comment]
Me neither :)
