### ISSUE TITLE
Not loading css

### ISSUE THREAD

**Issue by abel406** [siwapp/siwapp-sf3#66]
Hi  to all contributors and developers.

I recently made an installation and after getting it to work, i noticed it can't load the css files which exist in the folders. Might that have something to do to the way you are using to load assets in the templates ?

I am using a virtual host. Maybe the assets should be in the web folder.

Greetings.

Here is an screen shot
![no css loading in siwapp-sf3-master](https://cloud.githubusercontent.com/assets/3779394/21331101/c995c866-c60e-11e6-8cda-5363a26d251b.jpg)

**Comment by ParisLiakos** [comment]
Hello!

Did you run the assets dump command?

`php bin/console assetic:dump --env=prod`

**Comment by abel406** [comment]
Thank you @ParisLiakos. I did not. I run `php bin/console assets:install` instead, but after your quick answer, i fallowed your suggestion and it worked smoothly.
