### ISSUE TITLE
[Bug] Error 404 when printing "pending" estimates

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#73]
When clicking the "Save and print" button on estimates with pending status, such as the "Smith and Co." estimate (from the demo data), the new tab opens with a 404 Not Found error.

Error log:

`request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find Invoice entity." at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 301 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find Invoice entity. at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:301)"} []`

**Comment by ParisLiakos** [comment]
Good find, thanks
