### ISSUE TITLE
1.0 Release

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#77]
As far as I know, there are no known issues left to fix. Also, the docs have been polished already and translations have been completed.

I was wondering... Is there any thing else planned before 1.0? Can we expect a release before the new year?
Thanks!

**Comment by ParisLiakos** [comment]
Just added the new "Help" link, which needs translation. Other than that, i also think we are pretty much ready. I will now freeze string changes so we dont have to update translations more.. And maybe we target 31-12 for release? :)

**Comment by ParisLiakos** [comment]
Tagged https://github.com/siwapp/siwapp-sf3/releases/tag/1.0.0-beta

From now on, bug fixes, css fixes and translations will be merged

**Comment by JMCA2** [comment]
Sounds great :)

**Comment by JMCA2** [comment]
Translated "Help" into Spanish: #79

**Comment by JMCA2** [comment]
I'll be doing extensive testing trying to find any remaining issue in need of polishing, and report them tomorrow.

**Comment by ParisLiakos** [comment]
Thank you! It really looks good now. I will start some general testing and when i am done i will tag and release v1.0.0. Will also create some zip files for shared hosting that include wkhtmltopdf binaries

**Comment by ParisLiakos** [comment]
Happy new year :)

**Comment by JMCA2** [comment]
Congrats on the 1.0 release! ✨ 💥 🎆  Awesome work getting the legacy app ready for 2017 and modern times :)
