### ISSUE TITLE
[Bug] Reset password email not received

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#83]
When using the forgot password feature, I am not receiving the reset link email.
No error on logs.

**Comment by ParisLiakos** [comment]
Hmm i have only tested it locally, will try it on a live server shortly. 
Did you check your profile settings to see that the email is the correct one there, and your spam folder in your email?

**Comment by JMCA2** [comment]
The emails are being sent indeed. But from webmaster <webmaster@example.com>. These emails are blocked (not even delivered to spam) by Gmail because of example.com SPF records not allowing emails sent from their domain if they don't match their IP address.

The reset emails should be sent from COMPANY_NAME <company_email> instead.

**Comment by JMCA2** [comment]
It's seems to be using the default FOSUserBundle settings http://symfony.com/doc/current/bundles/FOSUserBundle/configuration_reference.html
