### ISSUE TITLE
Locale dropdown improvements

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#85]
- [ ] When changing other user settings (such as email), selecting locale again is required. It shouldn't be needed to selecting every time.

- [ ] Only the locales available (en, es, el, ro) should be listed in the dropdown.

**Comment by ParisLiakos** [comment]
> When changing other user settings (such as email), selecting locale again is required. It shouldn't be needed to selecting every time.
I didnt manage to reproduce this. if i change email or username the locale is still there. 

> Only the locales available (en, es, el, ro) should be listed in the dropdown.
I think we should have all locale available since they do not affect only the translations but also currency and date format

**Comment by JMCA2** [comment]
> When changing other user settings (such as email), selecting locale again is required. It shouldn't be needed to selecting every time.
I realized it just happens on the first time, which is right so the user is forced to select his locale.

> I think we should have all locale available since they do not affect only the translations but also currency and date format

Oh right, didn't know it also affected formats. My bad. Nothing to fix then :P
