### ISSUE TITLE
Error migrating database from v0.4.1

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#92]
When migrating to 1.0 a database containing 2 customers entries without name (but with email), the following happens:

> [Doctrine\DBAL\Exception\NotNullConstraintViolationException]
  An exception occurred while executing 'INSERT INTO invoice (customer_name,
  customer_identification, customer_email, invoicing_address, shipping_addres
  s, contact_person, terms, notes, base_amount, discount_amount, net_amount,
  gross_amount, paid_amount, tax_amount, series_id, sent_by_email, number, is
  sue_date, due_date, closed, status, created_at, updated_at, customer_id) VA
  LUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
  ?)' with params [null, null, null, null, null, null, null, null, 0, 0, 0, 0
  , 0, 0, null, "0", null, "2017-01-01", "2017-01-01", null, "0", "2013-09-24
   14:50:12", "2013-09-24 14:50:12", null]:
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'customer_name
  ' cannot be null
> [Doctrine\DBAL\Driver\PDOException]

 > SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'customer_name
  ' cannot be null

  >[PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'customer_name
  ' cannot be null

**Comment by ParisLiakos** [comment]
Hmm, weird, this is actually trying to create empty rows

**Comment by ParisLiakos** [comment]
I believe that the old app was creating empty customer records. We should not import those. The commit above should take care of that

**Comment by JMCA2** [comment]
Ok, thanks!
