### ISSUE TITLE
[Bug] Problems with comma as decimal separator

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#94]
When using the es_ES locale (Spanish as many other languages, uses commas as decimal mark), setting a quantity such as "0,5" on an item line isn't recognized and typing 0.5 is needed.

Also, setting a unitary price such as 9,99 is recognized as 9,00. Commas/dots usage should be consistent. Since the app shows ammounts with commas, it should also work well with comma-separated amounts input.

**Comment by ParisLiakos** [comment]
Thanks for the report! Should be fixed now

**Comment by JMCA2** [comment]
Thanks for the fix!
Just did some testing. It's working well now for the unitary cost, but not for the quantity number. For example, 0,25 gets converted to 0 when saving.

**Comment by ParisLiakos** [comment]
Actually that is expected, since quantity is integer :/ It does not support decimal values at all.
