### ISSUE TITLE
[Docs] Updating to new version

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#96]
The docs are missing instructions on how to update to the latest app version (such as v1.0.1). Only upgrading from the old v0.4 app is covered.

**Comment by ParisLiakos** [comment]
Yeah, good point, i wanted to add it, but realized that could not be updated with composer :(
So for now i will just suggest to people to replace the `src/` folder only manually.
And then in v2 i will update siwapp structure so updating via composer is possible.
