### ISSUE TITLE
user name password

### ISSUE THREAD

**Issue by mpvshameem** [siwapp/siwapp-sf3#97]
after installing i am not able to login , what will be the user id and password, please help

**Comment by JMCA2** [comment]
@mpvshameem You need to create the user with:
`$ php bin/console fos:user:create admin mail@example.com 1234 --super-admin`
As per the documentation on https://github.com/siwapp/siwapp-sf3/wiki/Installation.

In that command, _admin_ would be the user and _1234_ the password.
