### ISSUE TITLE
[Bug] "Save and send by email" saving as draft on new invoices

### ISSUE THREAD

**Issue by JMCA2** [siwapp/siwapp-sf3#98]
Steps to reproduce:
1. Visit the create new invoice page.
2. Fill the invoice fields.
3. Press "Save and send by email".

What happens: The invoice is saved as a draft.
What should happen: The invoice is saved as a non-draft invoice and is sent by email

**Comment by ParisLiakos** [comment]
Hmm actually the send as email in the new invoice page, is not sending any email, it just saves the invoice. xD Two bugs in one
